/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package setting;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import simrskhanza.DlgPeriksaLaboratorium;

/**
 *
 * @author Dinda Setia N
 */
public class DlgHitungLab extends javax.swing.JFrame {
    String HitungLabJk, HitungLabUmur;
    public DlgHitungLab(String PeriksaLabJk, String PeriksaLabUmur) {
        initComponents();
        HitungLabJk = PeriksaLabJk;
        HitungLabUmur = PeriksaLabUmur;        
        Tjk.setText(HitungLabJk);
        Tumur.setText(HitungLabUmur);
            isCek();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jPanel1 = new javax.swing.JPanel();
        panelBiasa1 = new widget.PanelBiasa();
        label3 = new widget.Label();
        label1 = new widget.Label();
        label2 = new widget.Label();
        Tjk = new widget.TextBox();
        Tsc = new widget.TextBox();
        Tumur = new widget.TextBox();
        label4 = new widget.Label();
        Thasil = new widget.TextBox();
        BtnKeluar = new widget.Button();
        label5 = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        internalFrame1.setLayout(new java.awt.BorderLayout());

        label3.setText("Umur :");

        label1.setText("Estimated GFR by 2021 CKD-EPI Creatinine :");

        label2.setText("Jenis Kelamin :");

        Tjk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tjk.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        Tsc.setToolTipText("Norm : 0.7 - 1.3");
        Tsc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tsc.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        Tsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TscKeyPressed(evt);
            }
        });

        Tumur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tumur.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        label4.setText("mg/dL");

        Thasil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Thasil.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });

        label5.setText("Serum creatinine  : ");

        javax.swing.GroupLayout panelBiasa1Layout = new javax.swing.GroupLayout(panelBiasa1);
        panelBiasa1.setLayout(panelBiasa1Layout);
        panelBiasa1Layout.setHorizontalGroup(
            panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBiasa1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tsc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBiasa1Layout.createSequentialGroup()
                            .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelBiasa1Layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tumur, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tjk, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelBiasa1Layout.createSequentialGroup()
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Thasil, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(6, 6, 6))))
                .addGap(14, 26, Short.MAX_VALUE))
        );
        panelBiasa1Layout.setVerticalGroup(
            panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tumur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelBiasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelBiasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        internalFrame1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed

    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void TscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TscKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if (Tsc.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nilai SC Belum di Inputkan !!!");
                isEmpty();
            }else{
                double nilai;
                double nilai1 = 0.9;
                double nilai2 = 0.7;
                double jumlah;
                double umur;
                nilai = Double.valueOf(Tsc.getText());
                umur = Double.valueOf(Tumur.getText());
                if (Tjk.getText().equals("Laki-Laki") && (nilai <= nilai1)){
                    jumlah = 142 * (Math.pow((nilai/nilai1),(-0.302))) * Math.pow(0.9938, umur);               
                    Thasil.setText(String.valueOf((String.format("%.2f", jumlah))));
                }else if (Tjk.getText().equals("Laki-Laki") && (nilai > nilai1)){
                    jumlah = 142 * (Math.pow((nilai/nilai1),(-1.200))) * Math.pow(0.9938, umur);
                    Thasil.setText(String.valueOf((String.format("%.2f", jumlah))));
                }else if (Tjk.getText().equals("Perempuan") && (nilai <= nilai2)){
                    jumlah = 142 * (Math.pow((nilai/nilai2),(-0.241))) * Math.pow(0.9938, umur) * 1012;
                    Thasil.setText(String.valueOf((String.format("%.2f", jumlah))));
                }else if (Tjk.getText().equals("Perempuan") && (nilai > nilai2)){
                    jumlah = 142 * (Math.pow((nilai/nilai2),(-1.200))) * Math.pow(0.9938, umur) * 1012;
                    Thasil.setText(String.valueOf((String.format("%.2f", jumlah))));
                }               
            }
        }
    }//GEN-LAST:event_TscKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new DlgHitungLab().setVisible(true);
            }            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.TextBox Thasil;
    public widget.TextBox Tjk;
    private widget.TextBox Tsc;
    private widget.TextBox Tumur;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JPanel jPanel1;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label3;
    private widget.Label label4;
    private widget.Label label5;
    private widget.PanelBiasa panelBiasa1;
    // End of variables declaration//GEN-END:variables
    public void isCek(){
        Tjk.setEnabled(false);
        Tumur.setEnabled(false);
//        Thasil.setEnabled(false);
    }
    
    public void isEmpty(){
        Thasil.setText("");
    }
}
